spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-store?createDatabaseIfNotExist=true
    username: root
    password: mysql
  flyway:
    repair: true

google:
  apiUrl: googlepay.com
  supportedCurrencies: GBP,EUR,USD

app:
  page-size: 10

payment:
  gateway: google

email:
  host: gmail
  port: 2020